name: Publish to DockerHub
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Airliftd release tag'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build and publish Docker image
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            snowled/docker-airliftd
          tags: |
            type=semver,pattern={{version}},value=${{ github.event.inputs.release_tag }}
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
          build-args: |
            RELEASE_TAG=${{ github.event.inputs.release_tag }}
          tags: ${{ steps.meta.outputs.tags }}
